### ISSUE TITLE
Has anyeone ever encountered

### ISSUE THREAD

**Issue by carlosIbsweb** [akeeba/plg_filesystem_s3#13]
Has anyone ever encountered, when uploading any file in Joomla, the file not being sent with its type to the plugin, resulting in the plugin defaulting to octet-stream? No joomla 4

**Comment by nikosdion** [comment]
The problem is that Joomla sends a binary stream to the adapter's `createFile` method without any MIME type information, or the original filename. 

Because of that, the only option to determine the MIME type of the content would be using the FileInfo extension (namely, the `finfo_buffer` function). However, this is not commonly enabled on commercial hosting. Therefore, this feature was never implemented.

The correct approach would be for Joomla! to provide this information to filesystem adapters. Unfortunately, the implementation of those adapters appears to have been made by people who either only thought of the regular server filesystem use case, or put unwarranted trust on what commercial hosting providers would enable by default and what users of commercial hosting could do by themselves.

**Comment by tampe125** [comment]
@carlosIbsweb I'm trying to replicate the problem in order to fix it, but in my tests everything seems to be working fine.  
I uploaded a PNG image in the Media Manager, it was correctly uploaded as PNG image and recognized as such inside S3 bucket.  

Can you please provide more details on how to replicate the issue? How are you uploading the file?

**Comment by nikosdion** [comment]
I was able to reproduce the issue, and it happens for the reason I had [previously explained](https://github.com/akeeba/plg_filesystem_s3/issues/13#issuecomment-2045345958).

Normally, Amazon S3 proper will see there is no `Content-Type` header and fall back to its own magic MIME detection for downloads. But I can see how third-party services and, in some cases, Amazon S3 itself would fall back to `application/octet-stream` which is not a very nice experience.

Instead of reinventing the wheel, I decided to use the excellent `league/mime-type-detection` library to do the MIME detection. If your server has the PHP `finfo` extension installed and enabled it will use it to detect the MIME type based on the actual file content. This is the absolute best way to do it. If the `finfo` extension is not enabled, we will fall back to detecting the MIME type based on the file extension _of the file being uploaded_, i.e. the name the file will have on S3. This is okay for most cases, but not very accurate. If all else fails, we fall back to the previous behaviour: let S3 figure it out, which will sometimes fall back to `application/octet-stream`.

I am wrapping up a few things and will release a new version in a few minutes.

Thank you, @carlosIbsweb for the report!
