### ISSUE TITLE
Question, i cannot create a folder

### ISSUE THREAD

**Issue by cloudfaction** [akeeba/plg_filesystem_s3#16]
it throws this error (i installed the latest version, joomla 4, PHP 7.4)

Akeeba\S3\Connector::putObject(): [500] MissingContentLength:You must provide the Content-Length HTTP header. Debug info: SimpleXMLElement Object ( [Code] => MissingContentLength [Message] => You must provide the Content-Length HTTP header. [RequestId] => NXKZGTZ84KNJ4YFY [HostId] => uyGm6/b66Yn/hdQou58ogIOUU8XxzVnGRauTVCrxogpcnICcwbS1ZCbCvmmFQKXa7e8+GtezSNE= )

**Comment by nikosdion** [comment]
Open the file `plugins/filesystem/s3/src/Adapter/S3Filesystem.php`

Find line 581 and change it from

```php
$dummy = '';
```

to 

```php
$dummy = '.';
```

This must be a very recent change to Amazon S3, because the empty file trick worked fine between 2010 (when I first implemented it) up until two months ago when I last tried creating a folder on S3.

**Comment by cloudfaction** [comment]
thx, problem solved!

Met vriendelijke groet,

Cloudfaction, internetspecialisten

Maarten Blokdijk
Korenaar 55
3224XD Hellevoetsluis

M: 06 - 247 59 222
W: https://www.cloudfaction.nl
Volg ons op twitter: @cloudfaction


Kamer van Koophandel: 56770065




Op di 13 aug 2024 om 15:01 schreef Nicholas K. Dionysopoulos <
***@***.***>:
