### ISSUE TITLE
bucket name does not accept dots

### ISSUE THREAD

**Issue by albertmoreno** [akeeba/plg_filesystem_s3#2]
### Steps to reproduce the issue

I place on bucket name media.icm.es (my name is similar)
And i can't save, i write down another name and it saves correctly

### Expected result

save bucket name correctly

### Actual result
save bucket name error

### System information

* **Joomla! version**: 4
* **Joomla! backend template**: 
* **Joomla! frontend template**: 
* **PHP version**: 8
* **Browser (name and version)**:

**Comment by nikosdion** [comment]
Already documented in https://github.com/akeeba/plg_filesystem_s3/blob/development/docs/caveats.md#bucket-naming

> Furthermore, you cannot use dots in your bucket names even though the Amazon Web Services Console lets you create buckets with dots in their names.
>
> These are not arbitrary requirements. They stem from how the Amazon S3 API actually works using the subdomain access method Amazon recommends. In fact, the subdomain method is the only one accepted in regions which were created after Amazon introduced the S3 V4 signature method. Allowing you to use bucket names in MixedCase or with.dots would cause an instant and non-obvious failure which would be hard or impossible to debug.

**Comment by nikosdion** [comment]
To make this even more clear, Amazon AWS does not let you use buckets with dots in their names outside very specific regions (basically, the original ten or so regions which predate Amazon's V4 signature method). It still lets you create buckets with dots in their names because some older regions can still be accessed with the V2 signature method which does allow for buckets with dots in their names. However, the V2 signature method is being retired.

You _could_ try using the v2 signature method in the plugin's options, in case your region supports v2 signatures, but this might still fail — the behaviour is region-specific, unfortunately. The best way to avoid that is renaming your bucket to use dashes or underscores instead of dots. So, instead of `foo.example.com` use `foo_example_com` or `foo-example-com` as your bucket's name.
