### ISSUE TITLE
Could not connect to the remote site error for J3 connector

### ISSUE THREAD

**Issue by Bodge-IT** [akeeba/plg_filesystem_s3#8]
### Steps to reproduce the issue
Install J3 panopticon plugin to a J3.10.12 site.
With details from plugin, attempt to create site entry on an installed Panopticon server

### Expected result
A saved entry for the site **Whether or not a connection is actually possible.
Establish a connection to the remote site and configure for use.

### Actual result
"Could not connect to the remote site" error
Warning about requirement for "Web Services - Installer" plugin on remote site
Unable to save entry due to failed connection (user experience impacted).  I would rather see an entry with warning about not connecting than not being able to save at all.

### Troubleshooting already performed
Checked I had installed the correct plugin.
Configured Admin Tools to allow access to panopticon_api directory (inc php)
Configured WAF to allow domain of panopticon server
Both systems are actually running on same server 

### System information

* **Joomla! version**: 3.10.12
* **Joomla! backend template**: Isis
* **Joomla! frontend template**: Helium (Gantry)
* **PHP version**: 7.4.33
* **Browser (name and version)**: FF 118.01

**Comment by nikosdion** [comment]
What you describe is the intended and documented behaviour. It is not a bug.

Being able to save despite a connection problem means that you are never notified about a connection problem, or its probable root cause (which is what Panopticon is currently doing). As a result, users would think that Panopticon is broken when the actual reason is a connection problem that has nothing to do with Panopticon itself. Beyond that, not being able to communicate to the user the nature of the connection problem makes resolution really hard, as there are _a lot_ of possible reasons for it, and nobody is willing to follow a troubleshooting document that's ten densely printed pages.

So, no, far from being a bug, it's a desirable feature.
